#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export GOPATH=$HOME/.go
export ZDOTDIR="$HOME/.zsh"
export GPG_TTY=$(tty)
export CURL_HOME="$HOME/.config/curl"
export PIP_CONFIG_FILE="$HOME/.config/pip/config"
export ANDROID_SDK_ROOT=/usr/local/share/android-sdk
export MBOX_DEBUG_DEVICE_UDID='00008020-001309A10E12002E'
