#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export ZDOTDIR="$HOME/.zsh"
export CURL_HOME="$HOME/.config"
export PIP_CONFIG_FILE="$HOME/.config/pip/pip.conf"
export GPG_TTY=$(tty)
