#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export ZDOTDIR="$HOME/.zsh"
export CURL_HOME="$HOME/.config/curl"
export PIP_CONFIG_FILE="$HOME/.config/pip/config"
export GOPATH=$HOME/.go
export GPG_TTY=$(tty)
