#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
source "$ZDOTDIR/prezto/init.zsh"

# Project shortcuts.
alias p='cd ~/.projects'
alias pswift='cd ~/.projects/Swift'
alias pios='cd ~/.projects/iOS'
alias pwebsite='cd ~/.projects/Website'

# Show hidden files in Finder.app.
alias findershow='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'
alias finderhide='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'

# Enable proxy.
function proxyon() {
  local host_port='127.0.0.1:8080'
  export http_proxy="http://$host_port"
  export https_proxy=$http_proxy
  git config --global http.proxy $host_port
  git config --global https.proxy $host_port
  echo 'proxy = "socks5://127.0.0.1:1080"' >! $HOME/.config/curlrc
}

# Disable proxy.
function proxyoff() {
  export http_proxy=''
  export https_proxy=''
  git config --global http.proxy ''
  git config --global https.proxy ''
  echo '' >! $HOME/.config/curlrc
}

# Enable proxy by default.
proxyon

# Open $(pwd)/$@ in Finder.app.
function opend() {
  if [ $# -eq 0 ]; then
		open .;
	else
		open "$@";
	fi;
}

# Reload shell.
function reload() {
  local compdump_files="$ZDOTDIR/.zcompdump*"

  if ls $compdump_files &> /dev/null; then
    rm -f $compdump_files
  fi

  exec $SHELL -l
}

# Reload shadowsocks.
function ss-reload() {
  local plist="$HOME/Library/LaunchAgents/org.shadowsocks-libev.plist"
  launchctl unload $plist
  launchctl load $plist
}

# File size calculator.
function filesize() {
	if du -b /dev/null > /dev/null 2>&1; then
		local arg=-sbh;
	else
		local arg=-sh;
	fi
	if [[ -n "$@" ]]; then
		du $arg -- "$@";
	else
		du $arg .[^.]* ./*;
	fi;
}

function xman() {
  open "x-man-page://$@"
}
